/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authRequestOtpRouteImport } from './routes/(auth)/request-otp'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedTicketIndexRouteImport } from './routes/_authenticated/ticket/index'
import { Route as AuthenticatedSubscriptionsIndexRouteImport } from './routes/_authenticated/subscriptions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRoles_permissionsIndexRouteImport } from './routes/_authenticated/roles_permissions/index'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedHealthReportsIndexRouteImport } from './routes/_authenticated/health-reports/index'
import { Route as AuthenticatedFcmTokensIndexRouteImport } from './routes/_authenticated/fcm-tokens/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedEmailTemplatesIndexRouteImport } from './routes/_authenticated/email-templates/index'
import { Route as AuthenticatedConfigurationIndexRouteImport } from './routes/_authenticated/configuration/index'
import { Route as AuthenticatedCaregiverInvitationsIndexRouteImport } from './routes/_authenticated/caregiver-invitations/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedActivityLogsIndexRouteImport } from './routes/_authenticated/activity-logs/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSubscriptionsSubscriptionIdRouteImport } from './routes/_authenticated/subscriptions/$subscriptionId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPlanPlanCodeRouteImport } from './routes/_authenticated/plan/$planCode'
import { Route as AuthenticatedEmailTemplatesNewRouteImport } from './routes/_authenticated/email-templates/new'
import { Route as AuthenticatedUsersCustomerIndexRouteImport } from './routes/_authenticated/users/customer/index'
import { Route as AuthenticatedUsersCaregiverIndexRouteImport } from './routes/_authenticated/users/caregiver/index'
import { Route as AuthenticatedTicketDetailTicketIdRouteImport } from './routes/_authenticated/ticket/detail.$ticketId'
import { Route as AuthenticatedEmailTemplatesEditTemplateIdRouteImport } from './routes/_authenticated/email-templates/edit.$templateId'
import { Route as AuthenticatedUsersCustomerDetailUserIdRouteImport } from './routes/_authenticated/users/customer/detail.$userId'
import { Route as AuthenticatedUsersCaregiverDetailCaregiverIdRouteImport } from './routes/_authenticated/users/caregiver/detail.$caregiverId'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authRequestOtpRoute = authRequestOtpRouteImport.update({
  id: '/(auth)/request-otp',
  path: '/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketIndexRoute =
  AuthenticatedTicketIndexRouteImport.update({
    id: '/ticket/',
    path: '/ticket/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionsIndexRoute =
  AuthenticatedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRoles_permissionsIndexRoute =
  AuthenticatedRoles_permissionsIndexRouteImport.update({
    id: '/roles_permissions/',
    path: '/roles_permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthReportsIndexRoute =
  AuthenticatedHealthReportsIndexRouteImport.update({
    id: '/health-reports/',
    path: '/health-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFcmTokensIndexRoute =
  AuthenticatedFcmTokensIndexRouteImport.update({
    id: '/fcm-tokens/',
    path: '/fcm-tokens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailTemplatesIndexRoute =
  AuthenticatedEmailTemplatesIndexRouteImport.update({
    id: '/email-templates/',
    path: '/email-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigurationIndexRoute =
  AuthenticatedConfigurationIndexRouteImport.update({
    id: '/configuration/',
    path: '/configuration/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaregiverInvitationsIndexRoute =
  AuthenticatedCaregiverInvitationsIndexRouteImport.update({
    id: '/caregiver-invitations/',
    path: '/caregiver-invitations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityLogsIndexRoute =
  AuthenticatedActivityLogsIndexRouteImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSubscriptionsSubscriptionIdRoute =
  AuthenticatedSubscriptionsSubscriptionIdRouteImport.update({
    id: '/subscriptions/$subscriptionId',
    path: '/subscriptions/$subscriptionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPlanPlanCodeRoute =
  AuthenticatedPlanPlanCodeRouteImport.update({
    id: '/plan/$planCode',
    path: '/plan/$planCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailTemplatesNewRoute =
  AuthenticatedEmailTemplatesNewRouteImport.update({
    id: '/email-templates/new',
    path: '/email-templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCustomerIndexRoute =
  AuthenticatedUsersCustomerIndexRouteImport.update({
    id: '/users/customer/',
    path: '/users/customer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCaregiverIndexRoute =
  AuthenticatedUsersCaregiverIndexRouteImport.update({
    id: '/users/caregiver/',
    path: '/users/caregiver/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketDetailTicketIdRoute =
  AuthenticatedTicketDetailTicketIdRouteImport.update({
    id: '/ticket/detail/$ticketId',
    path: '/ticket/detail/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailTemplatesEditTemplateIdRoute =
  AuthenticatedEmailTemplatesEditTemplateIdRouteImport.update({
    id: '/email-templates/edit/$templateId',
    path: '/email-templates/edit/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCustomerDetailUserIdRoute =
  AuthenticatedUsersCustomerDetailUserIdRouteImport.update({
    id: '/users/customer/detail/$userId',
    path: '/users/customer/detail/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCaregiverDetailCaregiverIdRoute =
  AuthenticatedUsersCaregiverDetailCaregiverIdRouteImport.update({
    id: '/users/caregiver/detail/$caregiverId',
    path: '/users/caregiver/detail/$caregiverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/request-otp': typeof authRequestOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/email-templates/new': typeof AuthenticatedEmailTemplatesNewRoute
  '/plan/$planCode': typeof AuthenticatedPlanPlanCodeRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/activity-logs': typeof AuthenticatedActivityLogsIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/caregiver-invitations': typeof AuthenticatedCaregiverInvitationsIndexRoute
  '/configuration': typeof AuthenticatedConfigurationIndexRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/fcm-tokens': typeof AuthenticatedFcmTokensIndexRoute
  '/health-reports': typeof AuthenticatedHealthReportsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/roles_permissions': typeof AuthenticatedRoles_permissionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/ticket': typeof AuthenticatedTicketIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/email-templates/edit/$templateId': typeof AuthenticatedEmailTemplatesEditTemplateIdRoute
  '/ticket/detail/$ticketId': typeof AuthenticatedTicketDetailTicketIdRoute
  '/users/caregiver': typeof AuthenticatedUsersCaregiverIndexRoute
  '/users/customer': typeof AuthenticatedUsersCustomerIndexRoute
  '/users/caregiver/detail/$caregiverId': typeof AuthenticatedUsersCaregiverDetailCaregiverIdRoute
  '/users/customer/detail/$userId': typeof AuthenticatedUsersCustomerDetailUserIdRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/request-otp': typeof authRequestOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/email-templates/new': typeof AuthenticatedEmailTemplatesNewRoute
  '/plan/$planCode': typeof AuthenticatedPlanPlanCodeRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/activity-logs': typeof AuthenticatedActivityLogsIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/caregiver-invitations': typeof AuthenticatedCaregiverInvitationsIndexRoute
  '/configuration': typeof AuthenticatedConfigurationIndexRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/fcm-tokens': typeof AuthenticatedFcmTokensIndexRoute
  '/health-reports': typeof AuthenticatedHealthReportsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/roles_permissions': typeof AuthenticatedRoles_permissionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsIndexRoute
  '/ticket': typeof AuthenticatedTicketIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/email-templates/edit/$templateId': typeof AuthenticatedEmailTemplatesEditTemplateIdRoute
  '/ticket/detail/$ticketId': typeof AuthenticatedTicketDetailTicketIdRoute
  '/users/caregiver': typeof AuthenticatedUsersCaregiverIndexRoute
  '/users/customer': typeof AuthenticatedUsersCustomerIndexRoute
  '/users/caregiver/detail/$caregiverId': typeof AuthenticatedUsersCaregiverDetailCaregiverIdRoute
  '/users/customer/detail/$userId': typeof AuthenticatedUsersCustomerDetailUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/request-otp': typeof authRequestOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/email-templates/new': typeof AuthenticatedEmailTemplatesNewRoute
  '/_authenticated/plan/$planCode': typeof AuthenticatedPlanPlanCodeRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/subscriptions/$subscriptionId': typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/activity-logs/': typeof AuthenticatedActivityLogsIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/caregiver-invitations/': typeof AuthenticatedCaregiverInvitationsIndexRoute
  '/_authenticated/configuration/': typeof AuthenticatedConfigurationIndexRoute
  '/_authenticated/email-templates/': typeof AuthenticatedEmailTemplatesIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/fcm-tokens/': typeof AuthenticatedFcmTokensIndexRoute
  '/_authenticated/health-reports/': typeof AuthenticatedHealthReportsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/_authenticated/roles_permissions/': typeof AuthenticatedRoles_permissionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/subscriptions/': typeof AuthenticatedSubscriptionsIndexRoute
  '/_authenticated/ticket/': typeof AuthenticatedTicketIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/email-templates/edit/$templateId': typeof AuthenticatedEmailTemplatesEditTemplateIdRoute
  '/_authenticated/ticket/detail/$ticketId': typeof AuthenticatedTicketDetailTicketIdRoute
  '/_authenticated/users/caregiver/': typeof AuthenticatedUsersCaregiverIndexRoute
  '/_authenticated/users/customer/': typeof AuthenticatedUsersCustomerIndexRoute
  '/_authenticated/users/caregiver/detail/$caregiverId': typeof AuthenticatedUsersCaregiverDetailCaregiverIdRoute
  '/_authenticated/users/customer/detail/$userId': typeof AuthenticatedUsersCustomerDetailUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/request-otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin-tools'
    | '/'
    | '/email-templates/new'
    | '/plan/$planCode'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subscriptions/$subscriptionId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/activity-logs'
    | '/alerts'
    | '/caregiver-invitations'
    | '/configuration'
    | '/email-templates'
    | '/events'
    | '/fcm-tokens'
    | '/health-reports'
    | '/help-center'
    | '/notifications'
    | '/plan'
    | '/roles_permissions'
    | '/settings/'
    | '/subscriptions'
    | '/ticket'
    | '/transactions'
    | '/email-templates/edit/$templateId'
    | '/ticket/detail/$ticketId'
    | '/users/caregiver'
    | '/users/customer'
    | '/users/caregiver/detail/$caregiverId'
    | '/users/customer/detail/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/request-otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/admin-tools'
    | '/'
    | '/email-templates/new'
    | '/plan/$planCode'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subscriptions/$subscriptionId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/activity-logs'
    | '/alerts'
    | '/caregiver-invitations'
    | '/configuration'
    | '/email-templates'
    | '/events'
    | '/fcm-tokens'
    | '/health-reports'
    | '/help-center'
    | '/notifications'
    | '/plan'
    | '/roles_permissions'
    | '/settings'
    | '/subscriptions'
    | '/ticket'
    | '/transactions'
    | '/email-templates/edit/$templateId'
    | '/ticket/detail/$ticketId'
    | '/users/caregiver'
    | '/users/customer'
    | '/users/caregiver/detail/$caregiverId'
    | '/users/customer/detail/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/request-otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/admin-tools'
    | '/_authenticated/'
    | '/_authenticated/email-templates/new'
    | '/_authenticated/plan/$planCode'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/subscriptions/$subscriptionId'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/activity-logs/'
    | '/_authenticated/alerts/'
    | '/_authenticated/caregiver-invitations/'
    | '/_authenticated/configuration/'
    | '/_authenticated/email-templates/'
    | '/_authenticated/events/'
    | '/_authenticated/fcm-tokens/'
    | '/_authenticated/health-reports/'
    | '/_authenticated/help-center/'
    | '/_authenticated/notifications/'
    | '/_authenticated/plan/'
    | '/_authenticated/roles_permissions/'
    | '/_authenticated/settings/'
    | '/_authenticated/subscriptions/'
    | '/_authenticated/ticket/'
    | '/_authenticated/transactions/'
    | '/_authenticated/email-templates/edit/$templateId'
    | '/_authenticated/ticket/detail/$ticketId'
    | '/_authenticated/users/caregiver/'
    | '/_authenticated/users/customer/'
    | '/_authenticated/users/caregiver/detail/$caregiverId'
    | '/_authenticated/users/customer/detail/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authRequestOtpRoute: typeof authRequestOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/request-otp': {
      id: '/(auth)/request-otp'
      path: '/request-otp'
      fullPath: '/request-otp'
      preLoaderRoute: typeof authRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/': {
      id: '/_authenticated/ticket/'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof AuthenticatedTicketIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions/': {
      id: '/_authenticated/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles_permissions/': {
      id: '/_authenticated/roles_permissions/'
      path: '/roles_permissions'
      fullPath: '/roles_permissions'
      preLoaderRoute: typeof AuthenticatedRoles_permissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-reports/': {
      id: '/_authenticated/health-reports/'
      path: '/health-reports'
      fullPath: '/health-reports'
      preLoaderRoute: typeof AuthenticatedHealthReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fcm-tokens/': {
      id: '/_authenticated/fcm-tokens/'
      path: '/fcm-tokens'
      fullPath: '/fcm-tokens'
      preLoaderRoute: typeof AuthenticatedFcmTokensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-templates/': {
      id: '/_authenticated/email-templates/'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuration/': {
      id: '/_authenticated/configuration/'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof AuthenticatedConfigurationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caregiver-invitations/': {
      id: '/_authenticated/caregiver-invitations/'
      path: '/caregiver-invitations'
      fullPath: '/caregiver-invitations'
      preLoaderRoute: typeof AuthenticatedCaregiverInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-logs/': {
      id: '/_authenticated/activity-logs/'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/subscriptions/$subscriptionId': {
      id: '/_authenticated/subscriptions/$subscriptionId'
      path: '/subscriptions/$subscriptionId'
      fullPath: '/subscriptions/$subscriptionId'
      preLoaderRoute: typeof AuthenticatedSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/plan/$planCode': {
      id: '/_authenticated/plan/$planCode'
      path: '/plan/$planCode'
      fullPath: '/plan/$planCode'
      preLoaderRoute: typeof AuthenticatedPlanPlanCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-templates/new': {
      id: '/_authenticated/email-templates/new'
      path: '/email-templates/new'
      fullPath: '/email-templates/new'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/customer/': {
      id: '/_authenticated/users/customer/'
      path: '/users/customer'
      fullPath: '/users/customer'
      preLoaderRoute: typeof AuthenticatedUsersCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/caregiver/': {
      id: '/_authenticated/users/caregiver/'
      path: '/users/caregiver'
      fullPath: '/users/caregiver'
      preLoaderRoute: typeof AuthenticatedUsersCaregiverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/detail/$ticketId': {
      id: '/_authenticated/ticket/detail/$ticketId'
      path: '/ticket/detail/$ticketId'
      fullPath: '/ticket/detail/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketDetailTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-templates/edit/$templateId': {
      id: '/_authenticated/email-templates/edit/$templateId'
      path: '/email-templates/edit/$templateId'
      fullPath: '/email-templates/edit/$templateId'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesEditTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/customer/detail/$userId': {
      id: '/_authenticated/users/customer/detail/$userId'
      path: '/users/customer/detail/$userId'
      fullPath: '/users/customer/detail/$userId'
      preLoaderRoute: typeof AuthenticatedUsersCustomerDetailUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/caregiver/detail/$caregiverId': {
      id: '/_authenticated/users/caregiver/detail/$caregiverId'
      path: '/users/caregiver/detail/$caregiverId'
      fullPath: '/users/caregiver/detail/$caregiverId'
      preLoaderRoute: typeof AuthenticatedUsersCaregiverDetailCaregiverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmailTemplatesNewRoute: typeof AuthenticatedEmailTemplatesNewRoute
  AuthenticatedPlanPlanCodeRoute: typeof AuthenticatedPlanPlanCodeRoute
  AuthenticatedSubscriptionsSubscriptionIdRoute: typeof AuthenticatedSubscriptionsSubscriptionIdRoute
  AuthenticatedActivityLogsIndexRoute: typeof AuthenticatedActivityLogsIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedCaregiverInvitationsIndexRoute: typeof AuthenticatedCaregiverInvitationsIndexRoute
  AuthenticatedConfigurationIndexRoute: typeof AuthenticatedConfigurationIndexRoute
  AuthenticatedEmailTemplatesIndexRoute: typeof AuthenticatedEmailTemplatesIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedFcmTokensIndexRoute: typeof AuthenticatedFcmTokensIndexRoute
  AuthenticatedHealthReportsIndexRoute: typeof AuthenticatedHealthReportsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
  AuthenticatedRoles_permissionsIndexRoute: typeof AuthenticatedRoles_permissionsIndexRoute
  AuthenticatedSubscriptionsIndexRoute: typeof AuthenticatedSubscriptionsIndexRoute
  AuthenticatedTicketIndexRoute: typeof AuthenticatedTicketIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedEmailTemplatesEditTemplateIdRoute: typeof AuthenticatedEmailTemplatesEditTemplateIdRoute
  AuthenticatedTicketDetailTicketIdRoute: typeof AuthenticatedTicketDetailTicketIdRoute
  AuthenticatedUsersCaregiverIndexRoute: typeof AuthenticatedUsersCaregiverIndexRoute
  AuthenticatedUsersCustomerIndexRoute: typeof AuthenticatedUsersCustomerIndexRoute
  AuthenticatedUsersCaregiverDetailCaregiverIdRoute: typeof AuthenticatedUsersCaregiverDetailCaregiverIdRoute
  AuthenticatedUsersCustomerDetailUserIdRoute: typeof AuthenticatedUsersCustomerDetailUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmailTemplatesNewRoute: AuthenticatedEmailTemplatesNewRoute,
  AuthenticatedPlanPlanCodeRoute: AuthenticatedPlanPlanCodeRoute,
  AuthenticatedSubscriptionsSubscriptionIdRoute:
    AuthenticatedSubscriptionsSubscriptionIdRoute,
  AuthenticatedActivityLogsIndexRoute: AuthenticatedActivityLogsIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedCaregiverInvitationsIndexRoute:
    AuthenticatedCaregiverInvitationsIndexRoute,
  AuthenticatedConfigurationIndexRoute: AuthenticatedConfigurationIndexRoute,
  AuthenticatedEmailTemplatesIndexRoute: AuthenticatedEmailTemplatesIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedFcmTokensIndexRoute: AuthenticatedFcmTokensIndexRoute,
  AuthenticatedHealthReportsIndexRoute: AuthenticatedHealthReportsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
  AuthenticatedRoles_permissionsIndexRoute:
    AuthenticatedRoles_permissionsIndexRoute,
  AuthenticatedSubscriptionsIndexRoute: AuthenticatedSubscriptionsIndexRoute,
  AuthenticatedTicketIndexRoute: AuthenticatedTicketIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedEmailTemplatesEditTemplateIdRoute:
    AuthenticatedEmailTemplatesEditTemplateIdRoute,
  AuthenticatedTicketDetailTicketIdRoute:
    AuthenticatedTicketDetailTicketIdRoute,
  AuthenticatedUsersCaregiverIndexRoute: AuthenticatedUsersCaregiverIndexRoute,
  AuthenticatedUsersCustomerIndexRoute: AuthenticatedUsersCustomerIndexRoute,
  AuthenticatedUsersCaregiverDetailCaregiverIdRoute:
    AuthenticatedUsersCaregiverDetailCaregiverIdRoute,
  AuthenticatedUsersCustomerDetailUserIdRoute:
    AuthenticatedUsersCustomerDetailUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authRequestOtpRoute: authRequestOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
