export const ErrorCodes = {
  // Generic
  ERROR: 'ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Payment-specific
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  VNPAY_INVALID_SIGNATURE: 'VNPAY_INVALID_SIGNATURE',
  VNPAY_CERT_EXPIRED: 'VNPAY_CERT_EXPIRED',

  // Auth / permissions
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SNAPSHOT_FORBIDDEN: 'SNAPSHOT_FORBIDDEN',
  ACTIVITY_LOGS_FORBIDDEN: 'ACTIVITY_LOGS_FORBIDDEN',

  // Domain-specific examples
  SUBSCRIPTION_NOT_ACTIVE: 'SUBSCRIPTION_NOT_ACTIVE',
  INSUFFICIENT_QUOTA: 'INSUFFICIENT_QUOTA',
  // Events / domain
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  CREATE_EVENT_FAILED: 'CREATE_EVENT_FAILED',
  CAREGIVER_OVERRIDE_FORBIDDEN: 'CAREGIVER_OVERRIDE_FORBIDDEN',
  UPDATE_CONFIRM_FAILED: 'UPDATE_CONFIRM_FAILED',
  CAREGIVER_DELETE_FORBIDDEN: 'CAREGIVER_DELETE_FORBIDDEN',
  UPLOAD_NO_FILE: 'UPLOAD_NO_FILE',
  FORBIDDEN_SELF_ONLY: 'FORBIDDEN_SELF_ONLY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export default ErrorCodes;
