// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43uCxiyMaxLn_2XUchbi2BRSqC5oDcXo',
    appId: '1:961808917290:web:207b84048d2a500af33453',
    messagingSenderId: '961808917290',
    projectId: 'vision-ai-ecfb4',
    authDomain: 'vision-ai-ecfb4.firebaseapp.com',
    storageBucket: 'vision-ai-ecfb4.firebasestorage.app',
    measurementId: 'G-R9LL3NF2QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBDyDDLnYSPdScjCUCeWDwtGOOIx8Zi4',
    appId: '1:961808917290:android:7f9bf304cb314b44f33453',
    messagingSenderId: '961808917290',
    projectId: 'vision-ai-ecfb4',
    storageBucket: 'vision-ai-ecfb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxX_RDPBg1aRbZenETdtbQ-7zPVeZu52Y',
    appId: '1:961808917290:ios:5bbbde9aa63a46b4f33453',
    messagingSenderId: '961808917290',
    projectId: 'vision-ai-ecfb4',
    storageBucket: 'vision-ai-ecfb4.firebasestorage.app',
    iosBundleId: 'com.example.detectCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxX_RDPBg1aRbZenETdtbQ-7zPVeZu52Y',
    appId: '1:961808917290:ios:5bbbde9aa63a46b4f33453',
    messagingSenderId: '961808917290',
    projectId: 'vision-ai-ecfb4',
    storageBucket: 'vision-ai-ecfb4.firebasestorage.app',
    iosBundleId: 'com.example.detectCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC43uCxiyMaxLn_2XUchbi2BRSqC5oDcXo',
    appId: '1:961808917290:web:686bcbc0cf4c3b8ef33453',
    messagingSenderId: '961808917290',
    projectId: 'vision-ai-ecfb4',
    authDomain: 'vision-ai-ecfb4.firebaseapp.com',
    storageBucket: 'vision-ai-ecfb4.firebasestorage.app',
    measurementId: 'G-6P6T2E53CM',
  );
}
